AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  etl-pipeline
  Sample SAM Template for etl-pipeline

Globals:
  Function:
    Timeout: 120
    MemorySize: 256

Resources:
  RecipePipelineMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/recipe_pipeline.asl.json
      DefinitionSubstitutions:
        GetUrlsFunctionArn: !GetAtt GetUrlsFunction.Arn
        HtmlParsingFunctionArn: !GetAtt HtmlParsingFunction.Arn
        CreateBatchFunctionArn: !GetAtt CreateBatchFunction.Arn
        CheckEmbeddingFunctionArn: !GetAtt CheckEmbeddingFunction.Arn
        CancelBatchFunctionArn: !GetAtt CancelBatchFunction.Arn
        TransVectorFunctionArn: !GetAtt TransVectorFunction.Arn
        UpdateVectorDBFunctionArn: !GetAtt UpdateVectorDBFunction.Arn

      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref GetUrlsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref HtmlParsingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateBatchFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckEmbeddingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CancelBatchFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref TransVectorFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateVectorDBFunction

  GetUrlsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/get_urls/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3

  HtmlParsingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/html_parsing/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3
  
  CreateBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/create_batch/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3

  CheckEmbeddingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/check_embedding/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3

  CancelBatchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/cancel_batch/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3

  TransVectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/trans_vector/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3

  UpdateVectorDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update_vectordb/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: arn:aws:iam::851725427984:role/lambda-fullaccess-s3


Outputs:
  RecipePipelineMachine:
    Description: "RecipePipelineMachine State machine ARN"
    Value: !Ref RecipePipelineMachine
  RecipePipelineMachineRoleArn:
    Description: "IAM Role created for RecipePipelineMachine based on the specified SAM Policy Templates"
    Value: !GetAtt RecipePipelineMachineRole.Arn
  Funcations:
    Description: "URLS"
    Value: !GetAtt GetUrlsFunction.Arn
