name: CI 

on: 
  push: 
    branches: 
      - "main" 
  pull_request: 
    branches: 
      - "main" 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with: 
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r ./etl-pipeline/tests/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Run Unit Tests
        run: pytest etl-pipeline/tests/unit/

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: 3.12 

      - name: Build SAM Application
        run: sam build --use-container --template etl-pipeline/template.yaml

      - name: Deploy SAM Application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset