name: CI_CD

on: 
  push: 
    branches: 
      - "main" 
    paths:
      - 'etl-pipeline/**'
  pull_request: 
    branches: 
      - "main"
    paths:
      - 'etl-pipeline/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with: 
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r ./etl-pipeline/tests/requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Run Unit Tests
        run: pytest etl-pipeline/tests/unit/

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.124.0

      # 테스트 환경에 Step Functions 배포
      - name: Deploy Step Functions to Test Environment
        run: |
          cd ./etl-pipeline
          sudo chmod +x ./build.sh
          ./build.sh
          sam deploy \
            --stack-name etl-pipeline-test \
            --no-confirm-changeset --no-fail-on-empty-changeset \
            --parameter-overrides Environment=Test

      # 테스트 환경에서 Integration 테스트 실행
      - name: Run Integration Test on Test Environment
        run: |
          export AWS_SAM_STACK_NAME=etl-pipeline-test
          pytest etl-pipeline/tests/integration/
        continue-on-error: true

      # 테스트 성공 시 운영 환경에 배포
      - name: Deploy Step Functions to Production Environment
        if: success()
        run: |
          cd ./etl-pipeline
          sam deploy \
            --stack-name etl-pipeline \
            --no-confirm-changeset --no-fail-on-empty-changeset \
            --parameter-overrides Environment=Production

      - name: Notify Failure
        if: failure()
        run: echo "Integration test failed! Step Functions was not deployed to production."